# Generated by Django 3.1.2 on 2020-10-11 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_names', models.CharField(max_length=100)),
                ('imageurl', models.TextField(null=True, validators=[django.core.validators.URLValidator()])),
                ('workplace_details', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('lattitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=100, null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('street_number', models.CharField(max_length=100, null=True)),
                ('suburb', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_contact_number', models.CharField(max_length=100)),
                ('secondary_contact_number', models.CharField(max_length=100, null=True)),
                ('next_of_kin_firstname', models.CharField(max_length=100, null=True)),
                ('next_of_kin_lastname', models.CharField(max_length=100, null=True)),
                ('next_of_kin_primary_contact_number', models.CharField(max_length=15, null=True)),
                ('next_of_kin_secondary_contact_number', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('profile_page', models.TextField(null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='QaphelaUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('user_type', models.CharField(choices=[('STANDARD', 'STANDARD'), ('LEGAL', 'LEGAL')], max_length=15)),
                ('imageurl', models.TextField(null=True, validators=[django.core.validators.URLValidator()])),
                ('is_dispatch_user', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('contact_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contactdetails')),
                ('social_profiles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.socialprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('ACCUSATION', 'ACCUSATION'), ('REPORT', 'REPORT'), ('ALLEGATION', 'ALLEGATION')], max_length=15)),
                ('occasion', models.CharField(choices=[('HOME', 'HOME'), ('WORK', 'WORK'), ('CHURCH', 'CHURCH'), ('EVENT', 'EVENT'), ('OTHER', 'OTHER')], max_length=15)),
                ('preview', models.TextField()),
                ('when', models.DateTimeField()),
                ('frequency', models.IntegerField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('case_status', models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED')], max_length=15)),
                ('settlement_type', models.CharField(choices=[('IN COURT', 'IN COURT'), ('OUT OF COURT', 'OUT OF COURT')], max_length=15, null=True)),
                ('perpetrators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.abuser')),
                ('reporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.qaphelauser')),
            ],
        ),
        migrations.AddField(
            model_name='abuser',
            name='contact_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contactdetails'),
        ),
        migrations.AddField(
            model_name='abuser',
            name='social_profiles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.socialprofiles'),
        ),
    ]
