# Generated by Django 3.1.2 on 2020-10-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='police_case_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
