# Generated by Django 3.1.2 on 2020-10-19 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='reference_url',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
