# Generated by Django 3.1.2 on 2020-10-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_case_police_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.qaphelauser'),
        ),
    ]
